# Site settings
name: Narasimhan DevarajanLakshmi(DL)
title: Narasimhan DevarajanLakshmi(DL) | Back-end Software Engineer
description: Design-minded Back-end software engineer focused on building beautiful interfaces and experiences
url: https://narasimhandl.github.io/
baseurl: ''
email: narasimhandl@gmail.com
cover: https://narasimhandl.github.io/img/og.png
logo: https://narasimhandl.github.io/img/emojis/technologist.png
resume: https://narasimhandl.github.io/resume.pdf
social:
  - title: email
    url: mailto:narasimhandl@gmail.com
  - title: twitter
    url: https://twitter.com/narasimhandev
  - title: instagram
    url: https://instagram.com/narasimhandl
  - title: codepen
    url: http://codepen.io/narasimhandl
  - title: github
    url: https://github.com/narasimhandl
  - title: linkedin
    url: https://www.linkedin.com/in/dl-n

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
